# Generated by Django 2.2.7 on 2019-11-26 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('usn', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('pass_out_batch', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('designation', models.CharField(max_length=200, null=True)),
                ('insta_link', models.URLField(max_length=250, null=True)),
                ('facebook_link', models.URLField(max_length=250, null=True)),
                ('github_link', models.URLField(max_length=250, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
