# Generated by Django 2.2.7 on 2019-11-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='dept_id',
            new_name='dept',
        ),
    ]
