# Generated by Django 2.2.7 on 2019-11-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pf_link',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
