# Generated by Django 2.2.7 on 2019-11-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_pf_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='li_link',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
