# Generated by Django 2.2.7 on 2019-11-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_bestalumnis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateField()),
                ('hosted_dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Department')),
            ],
        ),
    ]
